language: ruby
bundler_args: --without no_ci
before_install:
  - "gem update --system"
  - "gem update bundler"
script:
  - "bundle exec rspec"
os:
  - linux
  - osx
rvm:
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
matrix:
  include:
    - rvm: "2.3.0"
      script: "bundle exec rubocop"
branches:
  only:
    - master
    - develop
    - v4-stable
