name: Backup Documentation
baseurl: /backup
encoding: utf-8
exclude: ['Gemfile', 'Gemfile.lock']
kramdown:
  input: GFM

nav_v3: [
  ['Installation',              'installation'              ],
  ['Release Notes',             'release-notes'             ],
  [],
  ['Getting Started',           'getting-started'           ],
  ['Generator',                 'generator'                 ],
  ['Performing Backups',        'performing-backups'        ],
  ['Utilities',                 'utilities'                 ],
  ['Logging',                   'logging'                   ],
  ['Preconfigured Models',      'preconfigured-models'      ],
  ['Component Defaults',        'component-defaults'        ],
  ['Before/After Hooks',        'before-after-hooks'        ],
  ['Scheduling Backups',        'scheduling-backups'        ],
  ['Splitter',                  'splitter'                  ],
  [],
  ['Model Components',          '',                         '|'],
    ['Archives',                  'archives',                 'xxx|'],
    ['Databases',                 'databases',                'xxx|xxxxxxxx'],
      ['MySQL',                     'database-mysql'            ],
      ['PostgreSQL',                'database-postgresql'       ],
      ['MongoDB',                   'database-mongodb'          ],
      ['Redis',                     'database-redis'            ],
      ['Riak',                      'database-riak'             ],
    ['Compressors',               'compressors',              'xxx|xxxxxxxx'],
      ['Gzip',                      'compressor-gzip'           ],
      ['Bzip2',                     'compressor-bzip2'          ],
      ['Custom',                    'compressor-custom'         ],
    ['Encryptors',                'encryptors',               'xxx|xxxxxxxx'],
    ['OpenSSL',                     'encryptor-openssl'         ],
    ['GPG',                         'encryptor-gpg'             ],
    ['Storages',                  'storages',                 'xxx|xxxxxxxx'],
      ['CloudFiles',                'storage-cloudfiles'        ],
      ['Dropbox',                   'storage-dropbox'           ],
      ['S3',                        'storage-s3'                ],
      ['FTP',                       'storage-ftp'               ],
      ['SCP',                       'storage-scp'               ],
      ['SFTP',                      'storage-sftp'              ],
      ['RSync',                     'storage-rsync'             ],
      ['Local',                     'storage-local'             ],
    ['Syncers',                   'syncers',                  'xxx|xxxxxxxx'],
      ['CloudFiles',                'syncer-cloudfiles'         ],
      ['S3',                        'syncer-s3'                 ],
      ['RSync',                     'syncer-rsync'              ],
    ['Notifiers',                 'notifiers',                'xxx|xxxxxxxx'],
      ['Campfire',                  'notifier-campfire'         ],
      ['Hipchat',                   'notifier-hipchat'          ],
      ['HttpPost',                  'notifier-httppost'         ],
      ['Mail',                      'notifier-mail'             ],
      ['Nagios',                    'notifier-nagios'           ],
      ['Prowl',                     'notifier-prowl'            ],
      ['Pushover',                  'notifier-pushover'         ],
      ['Twitter',                   'notifier-twitter'          ]
]

nav_v4: [
  ['Installation',              'installation'              ],
  ['Upgrading',                 'upgrading'                 ],
  ['Release Notes',             'release-notes'             ],
  [],
  ['Getting Started',           'getting-started'           ],
  ['Generator',                 'generator'                 ],
  ['Performing Backups',        'performing-backups'        ],
  ['Utilities',                 'utilities'                 ],
  ['Logging',                   'logging'                   ],
  ['Preconfigured Models',      'preconfigured-models'      ],
  ['Component Defaults',        'component-defaults'        ],
  ['Before/After Hooks',        'before-after-hooks'        ],
  ['Scheduling Backups',        'scheduling-backups'        ],
  ['Splitter',                  'splitter'                  ],
  [],
  ['Model Components',          '',                         '|'],
    ['Archives',                  'archives',                 'xxx|'],
    ['Databases',                 'databases',                'xxx|xxxxxxxx'],
      ['MongoDB',                   'database-mongodb'          ],
      ['MySQL',                     'database-mysql'            ],
      ['OpenLDAP',                  'database-openldap'         ],
      ['PostgreSQL',                'database-postgresql'       ],
      ['Redis',                     'database-redis'            ],
      ['Riak',                      'database-riak'             ],
      ['SQLite',                    'database-sqlite'           ],
    ['Compressors',               'compressors',              'xxx|xxxxxxxx'],
      ['Bzip2',                     'compressor-bzip2'          ],
      ['Custom',                    'compressor-custom'         ],
      ['Gzip',                      'compressor-gzip'           ],
    ['Encryptors',                'encryptors',               'xxx|xxxxxxxx'],
    ['OpenSSL',                     'encryptor-openssl'         ],
    ['GPG',                         'encryptor-gpg'             ],
    ['Storages',                  'storages',                 'xxx|xxxxxxxx'],
      ['CloudFiles',                'storage-cloudfiles'        ],
      ['Dropbox',                   'storage-dropbox'           ],
      ['FTP',                       'storage-ftp'               ],
      ['Local',                     'storage-local'             ],
      ['SCP',                       'storage-scp'               ],
      ['SFTP',                      'storage-sftp'              ],
      ['RSync',                     'storage-rsync'             ],
      ['S3',                        'storage-s3'                ],
    ['Syncers',                   'syncers',                  'xxx|xxxxxxxx'],
      ['CloudFiles',                'syncer-cloudfiles'         ],
      ['RSync',                     'syncer-rsync'              ],
      ['S3',                        'syncer-s3'                 ],
    ['Notifiers',                 'notifiers',                'xxx|xxxxxxxx'],
      ['AWS SES',                   'notifier-ses'              ],
      ['Command',                   'notifier-command'          ],
      ['Campfire',                  'notifier-campfire'         ],
      ['DataDog',                   'notifier-datadog'          ],
      ['Flowdock',                  'notifier-flowdock'         ],
      ['HipChat',                   'notifier-hipchat'          ],
      ['HttpPost',                  'notifier-httppost'         ],
      ['Mail',                      'notifier-mail'             ],
      ['Nagios',                    'notifier-nagios'           ],
      ['Pagerduty',                 'notifier-pagerduty'        ],
      ['Prowl',                     'notifier-prowl'            ],
      ['Pushover',                  'notifier-pushover'         ],
      ['Slack',                     'notifier-slack'            ],
      ['Twitter',                   'notifier-twitter'          ],
      ['Zabbix',                    'notifier-zabbix'           ]
]
